### ISSUE TITLE
add optional param with log file path

### ISSUE THREAD

**Issue by jsilhan** [Tojaj/librepo#53]
add some optional param to Librepo with path to log file, please. It should print add debug messages to that file. The logs can be attached in connection bugs in dnf.

**Comment by rholy** [comment]
IIUIC, this blocks https://bugzilla.redhat.com/show_bug.cgi?id=1196629.
I'd like to ask you for raising the priority of this since these days mirrors are broken and because of that we are getting a lot of bugs against DNF. The first reply there is always: "can you please re-run the command with LIBREPO_DEBUG=1?". It would be easier/faster/more reliable to ask just for a log file.

**Comment by jsilhan** [comment]
Thanks Tomas for this. @mluscon , now you can integrate it with DNF (make it a high prio, please).
